version: '3.9'

services:
  backend:
    container_name: cardopt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cardopt
    ports:
      - 8080:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
